version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        expose:
            - "5432"
        networks:
            - app-network
        volumes:
            - ./postgres:/var/lib/postgresql

    uwsgi:
        container_name: uwsgi-nginx
        restart: unless-stopped
        depends_on: 
            - postgres
        build:
            context: ./app/
        image: uwsgi-nginx
        ports:
            - 80:80
        networks:
            - app-network
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - NETWORK=${NETWORK}
            - POSTGRES_HOST=${POSTGRES_HOST}


networks:
    app-network:
        driver: bridge
        name: app-network
